=== katiesvt/tilterview/spec/support/json_schemas/users/show.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "id_str": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "screen_name": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "profile_location": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "place_type": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "full_name": {
          "type": "string"
        },
        "country_code": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "contained_within": {
          "type": "array",
          "items": {}
        },
        "bounding_box": {
          "type": "null"
        },
        "attributes": {
          "type": "object",
          "properties": {}
        }
      },
      "required": [
        "id",
        "url",
        "place_type",
        "name",
        "full_name",
        "country_code",
        "country",
        "contained_within",
        "bounding_box",
        "attributes"
      ]
    },
    "description": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "entities": {
      "type": "object",
      "properties": {
        "url": {
          "type": "object",
          "properties": {
            "urls": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "url": {
                    "type": "string"
                  },
                  "expanded_url": {
                    "type": "string"
                  },
                  "display_url": {
                    "type": "string"
                  },
                  "indices": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    }
                  }
                },
                "required": [
                  "url",
                  "expanded_url",
                  "display_url",
                  "indices"
                ]
              }
            }
          },
          "required": [
            "urls"
          ]
        },
        "description": {
          "type": "object",
          "properties": {
            "urls": {
              "type": "array",
              "items": {}
            }
          },
          "required": [
            "urls"
          ]
        }
      },
      "required": [
        "url",
        "description"
      ]
    },
    "protected": {
      "type": "boolean"
    },
    "followers_count": {
      "type": "integer"
    },
    "friends_count": {
      "type": "integer"
    },
    "listed_count": {
      "type": "integer"
    },
    "created_at": {
      "type": "string"
    },
    "favourites_count": {
      "type": "integer"
    },
    "utc_offset": {
      "type": "integer"
    },
    "time_zone": {
      "type": "string"
    },
    "geo_enabled": {
      "type": "boolean"
    },
    "verified": {
      "type": "boolean"
    },
    "statuses_count": {
      "type": "integer"
    },
    "lang": {
      "type": "string"
    },
    "status": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "id_str": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "truncated": {
          "type": "boolean"
        },
        "entities": {
          "type": "object",
          "properties": {
            "hashtags": {
              "type": "array",
              "items": {}
            },
            "symbols": {
              "type": "array",
              "items": {}
            },
            "user_mentions": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "screen_name": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "id": {
                    "type": "integer"
                  },
                  "id_str": {
                    "type": "string"
                  },
                  "indices": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    }
                  }
                },
                "required": [
                  "screen_name",
                  "name",
                  "id",
                  "id_str",
                  "indices"
                ]
              }
            },
            "urls": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "url": {
                    "type": "string"
                  },
                  "expanded_url": {
                    "type": "string"
                  },
                  "display_url": {
                    "type": "string"
                  },
                  "indices": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    }
                  }
                },
                "required": [
                  "url",
                  "expanded_url",
                  "display_url",
                  "indices"
                ]
              }
            }
          },
          "required": [
            "hashtags",
            "symbols",
            "user_mentions",
            "urls"
          ]
        },
        "source": {
          "type": "string"
        },
        "in_reply_to_status_id": {
          "type": "null"
        },
        "in_reply_to_status_id_str": {
          "type": "null"
        },
        "in_reply_to_user_id": {
          "type": "null"
        },
        "in_reply_to_user_id_str": {
          "type": "null"
        },
        "in_reply_to_screen_name": {
          "type": "null"
        },
        "geo": {
          "type": "null"
        },
        "coordinates": {
          "type": "null"
        },
        "place": {
          "type": "null"
        },
        "contributors": {
          "type": "null"
        },
        "is_quote_status": {
          "type": "boolean"
        },
        "retweet_count": {
          "type": "integer"
        },
        "favorite_count": {
          "type": "integer"
        },
        "favorited": {
          "type": "boolean"
        },
        "retweeted": {
          "type": "boolean"
        },
        "possibly_sensitive": {
          "type": "boolean"
        },
        "lang": {
          "type": "string"
        }
      },
      "required": [
        "created_at",
        "id",
        "id_str",
        "text",
        "truncated",
        "entities",
        "source",
        "in_reply_to_status_id",
        "in_reply_to_status_id_str",
        "in_reply_to_user_id",
        "in_reply_to_user_id_str",
        "in_reply_to_screen_name",
        "geo",
        "coordinates",
        "place",
        "contributors",
        "is_quote_status",
        "retweet_count",
        "favorite_count",
        "favorited",
        "retweeted",
        "possibly_sensitive",
        "lang"
      ]
    },
    "contributors_enabled": {
      "type": "boolean"
    },
    "is_translator": {
      "type": "boolean"
    },
    "is_translation_enabled": {
      "type": "boolean"
    },
    "profile_background_color": {
      "type": "string"
    },
    "profile_background_image_url": {
      "type": "string"
    },
    "profile_background_image_url_https": {
      "type": "string"
    },
    "profile_background_tile": {
      "type": "boolean"
    },
    "profile_image_url": {
      "type": "string"
    },
    "profile_image_url_https": {
      "type": "string"
    },
    "profile_link_color": {
      "type": "string"
    },
    "profile_sidebar_border_color": {
      "type": "string"
    },
    "profile_sidebar_fill_color": {
      "type": "string"
    },
    "profile_text_color": {
      "type": "string"
    },
    "profile_use_background_image": {
      "type": "boolean"
    },
    "has_extended_profile": {
      "type": "boolean"
    },
    "default_profile": {
      "type": "boolean"
    },
    "default_profile_image": {
      "type": "boolean"
    },
    "following": {
      "type": "null"
    },
    "follow_request_sent": {
      "type": "null"
    },
    "notifications": {
      "type": "null"
    },
    "translator_type": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "id_str",
    "name",
    "screen_name",
    "location",
    "profile_location",
    "description",
    "url",
    "entities",
    "protected",
    "followers_count",
    "friends_count",
    "listed_count",
    "created_at",
    "favourites_count",
    "utc_offset",
    "time_zone",
    "geo_enabled",
    "verified",
    "statuses_count",
    "lang",
    "status",
    "contributors_enabled",
    "is_translator",
    "is_translation_enabled",
    "profile_background_color",
    "profile_background_image_url",
    "profile_background_image_url_https",
    "profile_background_tile",
    "profile_image_url",
    "profile_image_url_https",
    "profile_link_color",
    "profile_sidebar_border_color",
    "profile_sidebar_fill_color",
    "profile_text_color",
    "profile_use_background_image",
    "has_extended_profile",
    "default_profile",
    "default_profile_image",
    "following",
    "follow_request_sent",
    "notifications",
    "translator_type"
  ]
}

=== katiesvt/tilterview/spec/support/fixtures/1.1/users/show/katiesvt.json
{"id":297789562,"id_str":"297789562","name":"Katelyn Sievert","screen_name":"katiesvt","location":"Greater Vancouver","profile_location":{"id":"216dd1bcf824f9f7","url":"https:\/\/api.twitter.com\/1.1\/geo\/id\/216dd1bcf824f9f7.json","place_type":"unknown","name":"Greater Vancouver","full_name":"Greater Vancouver","country_code":"","country":"","contained_within":[],"bounding_box":null,"attributes":{}},"description":"Musician, plays and makes video games and I does webdev too","url":"https:\/\/t.co\/3xyx8gOn38","entities":{"url":{"urls":[{"url":"https:\/\/t.co\/3xyx8gOn38","expanded_url":"https:\/\/soundcloud.com\/katelyn-sievert\/","display_url":"soundcloud.com\/katelyn-siever\u2026","indices":[0,23]}]},"description":{"urls":[]}},"protected":false,"followers_count":24,"friends_count":80,"listed_count":1,"created_at":"Fri May 13 03:32:23 +0000 2011","favourites_count":246,"utc_offset":-28800,"time_zone":"Pacific Time (US & Canada)","geo_enabled":true,"verified":false,"statuses_count":114,"lang":"en","status":{"created_at":"Thu Nov 24 19:35:05 +0000 2016","id":801871783871807488,"id_str":"801871783871807488","text":"I added a video to a @YouTube playlist https:\/\/t.co\/sXfnZO7fux Even More of Far Cry: The First [canceled]","truncated":false,"entities":{"hashtags":[],"symbols":[],"user_mentions":[{"screen_name":"YouTube","name":"YouTube","id":10228272,"id_str":"10228272","indices":[21,29]}],"urls":[{"url":"https:\/\/t.co\/sXfnZO7fux","expanded_url":"http:\/\/youtu.be\/5PBcHbuJAKk?a","display_url":"youtu.be\/5PBcHbuJAKk?a","indices":[39,62]}]},"source":"\u003ca href=\"http:\/\/www.google.com\/\" rel=\"nofollow\"\u003eGoogle\u003c\/a\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"},"contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"000000","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/801501006550794240\/rRUrquC9_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/801501006550794240\/rRUrquC9_normal.jpg","profile_link_color":"3B94D9","profile_sidebar_border_color":"000000","profile_sidebar_fill_color":"000000","profile_text_color":"000000","profile_use_background_image":false,"has_extended_profile":false,"default_profile":false,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null,"translator_type":"none"}
